
export const GET_SUBMISSIONS = "GET_SUBMISSIONS";
export const DELETE_SUBMISSION = "DELETE_SUBMISSION";
export const ADD_SUBMISSION = "ADD_SUBMISSION";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const USER_LOADING = "USER_LOADING"; 
export const USER_LOADED = "USER_LOADED"; 
export const AUTH_ERROR = "AUTH_ERROR"; 
