
export const GET_SUBMISSIONS = "GET_SUBMISSIONS";
export const DELETE_SUBMISSION = "DELETE_SUBMISSION";
export const ADD_SUBMISSION = "ADD_SUBMISSION";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const USER_LOADING = "USER_LOADING"; 
export const USER_LOADED = "USER_LOADED"; 
export const AUTH_ERROR = "AUTH_ERROR"; 
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"; 
export const LOGIN_FAIL = "LOGIN_FAIL"; 
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"; 
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"; 
export const REGISTER_FAIL = "REGISTER_FAIL"; 
export const ACCOUNT_LOADING = "ACCOUNT_LOADING"; 
export const ACCOUNT_LOADED = "ACCOUNT_LOADED"; 
export const ACCOUNT_ERROR = "ACCOUNT_ERROR"; 
export const ADD_SCORE = "ADD_SCORE"; 
