# Generated by Django 3.2.9 on 2021-12-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_num_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='post_images'),
        ),
    ]
