# Generated by Django 3.2.9 on 2021-12-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_alter_submission_photo'),
        ('accounts', '0005_alter_account_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='submissions',
            field=models.ManyToManyField(to='submissions.Submission'),
        ),
    ]
