# Generated by Django 3.2.9 on 2021-12-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='score',
        ),
        migrations.AddField(
            model_name='account',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
