# Generated by Django 3.2.10 on 2021-12-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_photo_account_profile_photo'),
    ]

    operations = [
        
        
       
       
    ]
