# Generated by Django 3.2.10 on 2021-12-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211209_2339'),
    ]

    operations = [
       
    ]
