# Generated by Django 3.2.10 on 2021-12-09 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
         migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('community', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.community')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('profile_photo', models.ImageField(default='../media/default.jpg', upload_to='post_images')),
                ('num_submissions', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=150)),
            ],
        ),
       
        migrations.AddField(
            model_name='community',
            name='accounts',
            field=models.ManyToManyField(through='accounts.Membership', to='accounts.Account'),
        ),
    ]
