# Generated by Django 3.2.10 on 2021-12-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='name2',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
