# Generated by Django 3.2.10 on 2021-12-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='communities',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
