# Generated by Django 3.2.9 on 2021-12-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='num_submissions',
            field=models.IntegerField(default=0),
        ),
    ]
