# Generated by Django 3.2.10 on 2021-12-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_communities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_photo',
            field=models.ImageField(default='../media/default.jpg', upload_to='post_images'),
        ),
    ]
