# Generated by Django 3.2.10 on 2021-12-10 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_community_name2'),
    ]

    operations = [
         migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('community', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.community')),
            ],
        ),
        migrations.AlterField(
            model_name='membership',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
