# Generated by Django 3.2.10 on 2021-12-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
