# Generated by Django 3.2.10 on 2021-12-10 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_membership_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='account',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='community',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.community'),
        ),
    ]
