# Generated by Django 3.2.10 on 2021-12-11 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='communities',
        ),
    ]
