# Generated by Django 3.2.9 on 2021-12-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(default='../media/default.jpg', upload_to='post_images'),
        ),
    ]
