# Generated by Django 3.2.10 on 2021-12-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_communities'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='communities',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
