# Generated by Django 3.2.10 on 2021-12-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_communities'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_photo',
            field=models.ImageField(default='../media/default.jpg', upload_to='profile_photos'),
        ),
    ]
