# Generated by Django 3.2.10 on 2021-12-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211212_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_photo',
            field=models.ImageField(default='../media/default.jpg', upload_to='../media'),
        ),
    ]
