# Generated by Django 3.2.10 on 2021-12-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_photo',
            field=models.ImageField(default='../media/default.jpg', upload_to='profile_photos'),
        ),
    ]
