<<<<<<< HEAD
# Generated by Django 3.2.10 on 2021-12-14 22:18
=======
# Generated by Django 3.2.10 on 2021-12-15 18:10
>>>>>>> febda76fc940316fa391005d4270b08f0321d99b

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_photo',
            field=models.ImageField(default=0, upload_to='profile_images'),
        ),
    ]
