# Generated by Django 3.2.9 on 2021-12-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_photo_account_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='submissions',
        ),
        migrations.AddField(
            model_name='account',
            name='communities',
            field=models.ManyToManyField(to='accounts.Community'),
        ),
    ]
