# Generated by Django 3.2.9 on 2021-11-30 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userdata',
            new_name='User',
        ),
    ]
