# Generated by Django 3.2.9 on 2021-12-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20211205_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='photo',
        ),
    ]
