# Generated by Django 3.2.9 on 2021-12-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_submission_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='photo',
            field=models.ImageField(default=0, upload_to='submissions/images'),
        ),
    ]
