# Generated by Django 3.2.9 on 2021-12-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_alter_submission_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='photo',
            field=models.ImageField(default=0, upload_to='post_images'),
        ),
    ]
