# Generated by Django 3.2.10 on 2021-12-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_alter_submission_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
