# Generated by Django 3.2.10 on 2021-12-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_alter_submission_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='unit',
            field=models.CharField(default='', max_length=50),
        ),
    ]
