# Generated by Django 3.2.10 on 2021-12-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_submission_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='unit',
            field=models.CharField(default='Money', max_length=50),
        ),
    ]
