# Generated by Django 3.2.9 on 2021-12-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googlemaps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
