# Generated by Django 3.2.10 on 2021-12-09 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211209_1748'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='account',
            name='communities',
        ),
        migrations.AddField(
            model_name='account',
            name='heloo',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('community', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.community')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='accounts',
            field=models.ManyToManyField(through='accounts.Membership', to='accounts.Account'),
        ),
    ]
