# Generated by Django 3.2.10 on 2021-12-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211209_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='accounts',
        ),
        migrations.AddField(
            model_name='account',
            name='communities',
            field=models.ManyToManyField(to='accounts.Community'),
        ),
    ]
