# Generated by Django 3.2.10 on 2021-12-09 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211209_2311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
