# Generated by Django 3.2.10 on 2021-12-09 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delete_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='communities',
            new_name='communities1',
        ),
    ]
