# Generated by Django 3.2.10 on 2021-12-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_communities_account_communities1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='communities1',
            new_name='communities',
        ),
    ]
