# Generated by Django 3.2.10 on 2021-12-09 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_communities1_account_communities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='communities',
        ),
        migrations.RemoveField(
            model_name='account',
            name='heloo',
        ),
        migrations.RemoveField(
            model_name='account',
            name='num_submissions',
        ),
        migrations.RemoveField(
            model_name='account',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='account',
            name='score',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.RemoveField(
            model_name='community',
            name='name',
        ),
        migrations.RemoveField(
            model_name='community',
            name='zip_code',
        ),
    ]
